### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by rabimans** [wladich/elevation_server#3]
hi,
while trying to run **run make_data -hgt <PATH_TO_HGT_FILES> -out dem_tiles** it says **make_data: command not found** in ubuntu 20.04. 
any suggestions will be highly appreciable.

Thank you

**Comment by wladich** [comment]
In linux you can not simply run executable in current directory by name. You need to do one of the following:
- Place `make_data` binary to directory present in $PATH, for example `/usr/local/bin`
- Specify path to `make_data` binary. If it is in current directory then type `./make_data ...`

The `make_data` binary can be either built from source or downloaded from [latest release](https://github.com/wladich/elevation_server/releases/tag/1.2.0)

**Comment by rabimans** [comment]
Great... thanks.. it worked now.. 
trying next step in few minutes.
