### ISSUE TITLE
Response returned is NULL NULL

### ISSUE THREAD

**Issue by yalamber** [wladich/elevation_server#4]
Hello, I tried setting up server as instructions in Readme and seems to be working but for some reason response is always NULL NULL. 

curl https://elevations.example.com --data-binary $'49.18148 16.35126\n49.13545 16.33615'

response is NULL NULL

**Comment by wladich** [comment]
Normally server returns NULL for missing data (I forgot to mention it in readme). Did you supply hgt file for this point to `make_data`?

The file name should be N049E16.hgt

**Comment by yalamber** [comment]
Oh I got it now, I am downloading all hgt files, How big is your dem files? Is it too big if we want to support all continents?

**Comment by wladich** [comment]
The collection at viewfinderpanoramas.org is compressed in zip and is about 16 Gb. I think it is about 70-80 Gb when uncompressed. 

The resulting data file for elevation server is 19 Gb as it uses lz4 compression.

**Comment by yalamber** [comment]
Thanks, will try to build dem files for all hgt files

**Comment by yalamber** [comment]
Thanks @wladich  finally got server up with total data, Though there was issue with one file N63E008.hgt, other all files seems to be of size 2.9 MB but this one specifically was 25.9 MB and make_data command was failing after removing this was able to create dem files.

**Comment by wladich** [comment]
Looks like it was the same problem as in #2 - it is a dem file with 1"  resolution but olny 3" is supported

**Comment by yalamber** [comment]
Oh ok go it. seems to be working fine now. Great work by the way providing all these application as opensource. Thank you
